### ISSUE TITLE
How do i reset the settings?

### ISSUE THREAD

**Issue by spmredmi** [pontusab/wp-ftp-media-library#4]
I installed this plugin and connected a remote ftp server and it was working well :) but i only installed it for testing purpose and now i want to restore it back to home directory, i uninstalled the plugin but its still generating remote ftp urls :( but i think files are getting uploaded to my main server's upload folder

**Comment by ElectroLutz** [comment]
You have to unset the option "upload_url_path" on the All Settings page.

Here's a tutorial how to get there (taken from wordpress.org):

1. Go to (your site)/wp-admin/options.php.
2. Options are sorted by alphabetical order. Find out the options you want to change, edit it and click Save Changes button at the bottom of the page.
3. Or click any menu in the Dashboard to exit.

**Comment by spmredmi** [comment]
That worked, thanks :)
